<?php

namespace App;

use App\Scopes\LatestScope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['content','user_id'];

    protected $hidden = ['commentable_type','commentable_id'];

    public function commentable(){
        return $this->morphTo();
    }

    public function post(){
        return $this->belongsTo(Post::class);
    }

//    public function scopeComment(Builder $query){
//        return $query->where('post_id','>=','2');
//    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//        static::addGlobalScope(new LatestScope());

    }
    //
}
